name: Optic CI Template
description: | 
  A template for running Optic CI rules against your OpenAPI files.
  Fork this repository, and add your rules under src/ruleset.
  For more information join the beta at https://www.useoptic.com/

inputs:
  file:
    description: The OpenAPI file to evalute in this PR.
    required: true
  ruleset:
    description: The ruleset to apply to OpenAPI changes.
    required: false
    default: default

runs:
  using: composite
  steps:
    - name: Setup
      run: |
        echo "::group::Setup"
        yarn install
        yarn build
        echo "::endgroup::"
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: >-
        node $GITHUB_ACTION_PATH/build/index.js compare 
        --from ${{ github.event.pull_request.base.sha }}:${{ inputs.file }}
        --to ${{ github.event.pull_request.head.sha }}:${{ inputs.file }}
        --ruleset ${{ inputs.ruleset }}
        --github-annotations
      env:
        FORCE_COLOR: 2
      shell: bash
